#spring.application.name=RMS
#
#server.port=8009
#spring.datasource.url=jdbc:postgresql://localhost:5432/rms
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.application.name=RMS

# Active profile
spring.profiles.active=dev

# Swagger path
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs